name: cat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  cached_network_image: ^3.2.2
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.2.19
  flutter:
    sdk: flutter

flutter_native_splash:
  image: assets/images/cat_logo.png
  color: ffffff
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/place_holder.png
    - assets/images/cat_logo.png
